"""adding time created collumn in association table

Revision ID: 549fca4e50d2
Revises: 15152d55e08f
Create Date: 2024-07-11 10:33:41.937348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549fca4e50d2'
down_revision = '15152d55e08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookingservices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookingservices', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
